# Configuration file for NetlifyCMS visual editor
# It's here used only for blog posts and docs pages, to ease edits from external contributors
# for all options, see https://www.netlifycms.org/docs/configuration-options/

publish_mode: editorial_workflow  # do not commit directly, fork to a branch first and create a pull request, this is necessary for the open_authoring option

backend:
  name: github  # external contributions open_authoring option requires the use of github, it does not work with git-gateway (and hence other git platforms) yet (although there are alternatives through Netlify Identity): https://www.netlifycms.org/docs/open-authoring/
  repo: https://github.com/lrq3000/stackbit-gatsby-theme-diy-libris  # EDIT ME: path to the online repository to allow for external contributions, please update this to point to your repo
  branch: master
  open_authoring: true  # allow external contributors without having to first give them access to the repository, their edits will be made on their own github repository and create a pull request automatically through the UI

media_folder: static/images/uploads  # where media files such as images will be stored
public_folder: /images/uploads  # url to media files when deployed

# site_url: https://your-site.com  # edit and uncomment this line to enable previews
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg  # custom logo
# locale: 'en'  # UI language

collections:
  - name: blog  # used in routes, e.g., /admin/collections/blog
    label: Blog  # used in the UI
    folder: blog  # relative url where the editable documents are stored
    create: true  # allow users to create new documents in this collection
    slug: "{{title}}"  # filename template, the adequate file extension (e.g., .md) will be automatically added
    extension: md
    fields:  # fields for each document, usually in front matter, default type is string
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: docs
    label: Docs
    folder: docs
    create: true
    slug: "{{title}}"
    extension: md
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
